services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
      - simpletestrunner
    env_file:
      - .env
    networks:
      - mynetwork
    #extra_hosts:
    #  - "synaptic-k8s-01:192.168.38.251"

  simpletestrunner:
    build: ./testRunner
    expose:
      - "8082"
    networks:
      - mynetwork

  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - mynetwork

  db:
    image: postgres:17.5
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork
    ports:
      - "5432:5432"

volumes:
  pgdata:

networks:
  mynetwork:
