services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
      - simpletestrunner
    env_file:
      - .env
    networks:
      - mynetwork
    #volumes:
    #  - ./SimpleTestRunner:/app/SimpleTestRunner

  simpletestrunner:
    build: ./testRunner
    expose:
      - "8082"
    networks:
      - mynetwork
  db:
    image: postgres:17.5
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}    
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  pgdata:

networks:
  mynetwork:

